#!/usr/bin/env bash

## VARIABLES
THIS_DIR=$(cd "$(dirname "$0")"; pwd)
TDCLI='https://valtman.name/files/telegram-cli-1222'

## Print Colorful
# Print text in red
prtred() {
  printf '\e[1;31m%s\n\e[0;39;49m' "$@"
}
# Print text in green
prtgrn() {
  printf '\e[1;32m%s\n\e[0;39;49m' "$@"
}
# Print text in brown
prtbrown() {
  printf '\e[1;33m%s\n\e[0;39;49m' "$@"
}

# install Bot
install() {
  prtgrn '
  >> Do you want to install Essentials of Bot? (Y/N):
'
  read -rp ' ' install
  case "$install" in
    Y|y|بله)
      prtgrn "
 >> Fetching $TDCLI
"
      wget "$TDCLI" -O telegram-cli
      chmod +x telegram-cli
      prtgrn "
 >> Updating old packages
"
      sudo apt-get -y update && sudo apt-get -y upgrade 
      prtgrn "
 >> Installing Essentials packages
"
        sudo apt-get update
		sudo apt-get upgrade
        sudo apt-get install lua5.1 luarocks lua-socket lua-sec redis-server curl 
       sudo luarocks install oauth 
        sudo luarocks install redis-lua 
       sudo luarocks install lua-cjson 
       sudo luarocks install ansicolors 
       sudo luarocks install serpent 
       sudo luarocks install json-lua
       cd tg
		sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
		sudo apt-get install g++-4.7 -y c++-4.7 -y
		sudo apt-get update
		sudo apt-get upgrade
		sudo apt-get install libreadline-dev -y libconfig-dev -y libssl-dev -y lua5.2 -y liblua5.2-dev -y lua-socket -y lua-sec -y lua-expat -y libevent-dev -y make unzip git redis-server autoconf g++ -y libjansson-dev -y libpython-dev -y expat libexpat1-dev -y
		sudo apt-get install screen -y
		sudo apt-get install tmux -y
		sudo apt-get install libstdc++6 -y
		sudo apt-get install lua-lgi -y
		sudo apt-get install libnotify-dev -y
		wget https://valtman.name/files/telegram-cli-1222
		mv telegram-cli-1222 tgcli
		chmod +x tgcli
		cd ..
		chmod +x bot
		chmod +x tg
      prtgrn "
 >> Updating packages
"
      sudo apt-get -y update && sudo apt-get -y upgrade && sudo apt-get -y dist-upgrade && sudo apt-get -y autoremove
    ;;
    N|n|خیر)
      prtbrown '
 Canceling the operation
 '
    ;;
    *)
      prtred '
  Wrong command
 '
      install
    ;;
  esac
}

## MAIN ------------------------------------------------------------------------
# Make sure this script run inside Bot directory
cd "$THIS_DIR" || exit
case $1 in
  update)
    update
  ;;
  install)
    install
  ;;
  fix)
    fix
  ;;
  cli)
     while true ; do
      ./tg/tgcli -s ./bot/bot.lua
      sleep 10
     done
    ;;
  api)
     while true ; do
      lua helper.lua
      sleep 5
     done
  ;;
esac
